### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by boc-tothefuture** [digitaldan/jomnilink#23]
@digitaldan  - 
  Can we change the license away from GPL?  With the current license I am not sure if this can ever be shipped with something like openhab?  I don't know what license to suggest.. apache, eclipse?

**Comment by digitaldan** [comment]
Sorry i totally missed this.  Yes of course, i will change to EPL

**Comment by digitaldan** [comment]
https://github.com/digitaldan/jomnilink/commit/437e302f5f34cfc1257225f7ea95a6d4bda47796
