### ISSUE TITLE
Fix typo in NotificationListener

### ISSUE THREAD

**Issue by boc-tothefuture** [digitaldan/jomnilink#3]
Do we want to fix the method type in NotificationListener:
    public void objectStausNotification(ObjectStatus status) 

Change to:
    public void objectStatusNotification(ObjectStatus status) 

If we do want to fix it, do we want to deprecate the old method for a while but have both fire?

**Comment by digitaldan** [comment]
Good catch! I would rather just remove it, I don't think there is a very large base of people using the library, and if they bother to update to the latest version, i think its ok to ask them to update their code.
