### ISSUE TITLE
Temperatures return as int

### ISSUE THREAD

**Issue by ecdye** [digitaldan/jomnilink#31]
Shouldn't temperatures be returned as a double or float rather than as an int @digitaldan?

**Comment by digitaldan** [comment]
Can you be more specific ? This library is quite old, so I have not looked at in in a very long time .   Temp formats are returned in a Omni specific format if I remember correctly , is there a conversion method you are referring to ? Please reference the code in question if you have an issue , and a  pr would be welcome if you have a fix .

**Comment by digitaldan** [comment]
@ecdye if you can show me where you think there an issue, feel free to re-open, but please reference the code in question next time.
