### ISSUE TITLE
Migrate off Travis

### ISSUE THREAD

**Issue by ecdye** [digitaldan/jomnilink#38]
@digitaldan Just an FYI but Travis CI is no longer free and once you run out of your allotment of free minutes, you will have to pay. 

I would suggest migrating to GitHub Actions, there is a large amount of documentation available online at <https://docs.github.com/en/actions>.

Just a thought.

**Comment by digitaldan** [comment]
Yeah, its probably a good idea, we have been slowly moving other projects off as well.
