### ISSUE TITLE
Versioning and Releasing

### ISSUE THREAD

**Issue by boc-tothefuture** [digitaldan/jomnilink#4]
@digitaldan - 
  Do we need to figure out how to automatically release and version this library?  It would be nice to get this so its available in maven, etc (I guess through jfrog/bintray - but I have never done it).  I now that @craigham setup auto builds / releases for the binding.. Maybe he can help us out?

I am bringing this up because I need to change the library to support changes to thermostats in for omnilink 3.x.

**Comment by digitaldan** [comment]
👍  ,  as part of moving to maven, this was my intention as well.  I'll look at doing this soon.

**Comment by digitaldan** [comment]
FYI  have this mostly working and am able to push snapshot builds to sonatype (maven central), I just need to tweak a few things to make it publicly visible.

**Comment by craigham** [comment]
unfortunately I don't have experience with making libs available on the maven repos.  

I just use shippable to run auto-builds, and copy the artifacts to my S3 account.   Then the marketplace binding downloads from there via the eclipse marketplace entry.

**Comment by digitaldan** [comment]
Staging is now on Sonatype at https://oss.sonatype.org/content/repositories/snapshots/com/github/digitaldan/jomnilink/

I just pushed a 1.0 version to Central, it takes a bit for sonatype to publish it, once thats confirmed we can close this issue.

**Comment by digitaldan** [comment]
We are now in maven central
https://repo1.maven.org/maven2/com/github/digitaldan/jomnilink/1.0/

**Comment by digitaldan** [comment]
Also I have TravisCI now building everything (PR's, branches, etc..) and will auto deploy master to maven staging at https://oss.sonatype.org/content/repositories/snapshots/com/github/digitaldan/jomnilink/

**Comment by craigham** [comment]
@digitaldan nice.

**Comment by boc-tothefuture** [comment]
@digitaldan -
  Awesome. How do we update the version?  Is that in the maven file?
  Are we following semver?

**Comment by digitaldan** [comment]
right now snapshots get auto versioned, so we have 1.1.0-SNAPSHOT,  the build will remove the SNAPSHOT from that and append the build time.  For release we branch and add a real version number like 1.1.0 (no SNAPSHOT), this will trigger a release build.  This is all in the POM file.  I then need to log into Sonotype and promote it to maven central. 

Unfortunately, I just realized ( actually I forgot and then just googled and remembered) , that this does not help us with openHAB/ESH.  Unless something has changed, runtime dependencies can not be pulled from central, see https://groups.google.com/forum/#!topic/openhab/NgH_FlQARC0  

Regardless, i think its still good to have this auto building and pushing to somewhere

**Comment by boc-tothefuture** [comment]
Awesome.  Thanks for the summary.
