### ISSUE TITLE
Missing Console Beep Commands

### ISSUE THREAD

**Issue by boc-tothefuture** [digitaldan/jomnilink#7]
@digitaldan -
  I am not sure if you are following the openhab2 binding repo, so I am opening an issue here.
  I think that the console beep elements you added were not pushed back into this library.  This is making my build fail against your latest branch of the binding.  
  It was blocking my thermostat PR, but it looks like @craigham merged that PR anyway so I suspect that branch is now failing it's build.

**Comment by digitaldan** [comment]
Sorry about that, I missed a class for sure.  Try again now.
